services:
  db:
    image: 'postgres:15.2'
    container_name: db
    volumes:
      - /home/alina/3rd-course-ooa-d/src/main/resources/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - myenv.env
