#services:
#  database:
#    image: 'postgres:15.2'
#    ports:
#      - '15432:5432'
#    volumes:
#      - /home/alina/3rd-course-ooa-d/src/main/resources/db:/docker-entrypoint-initdb.d
#    environment:
#      - 'POSTGRES_USER=postgres'
#      - 'POSTGRES_DB=postgres'
#      - 'POSTGRES_PASSWORD=postgres'

services:
  db:
    image: 'postgres:15.2'
    container_name: db
    volumes:
      - /home/alina/3rd-course-ooa-d/src/main/resources/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
      - CLIENT_SECRET=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
      - MAIL_USERNAME=linacy.mail@gmail.com
      - ENABLE_SSL=false
      - DB_NAME=POSTGRESQL
      - REFRESH_SECRET=zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
      - SECRET_REFRESH=zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
      - CLIENT_ID_ANDROID=1055675266750-ifmol9tls9o0re7rura8hpcfit70hlcg.apps.googleusercontent.com
      - SECRET_ACCESS=qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      - SCHEMA_NAME=litera_vibe
      - ENABLE_HTTP2=false
      - ACCESS_SECRET=qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      - CLIENT_ID_WEB=1055675266750-b4i682d2uj1vt7cgi4s4e3poj90j5ep8.apps.googleusercontent.com
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - MAIL_PASSWORD=kdacomquvlzyeiwf
      - DATASOURCE_PASSWORD=postgres